#!/usr/bin/env python3
"""Agent code generator

Generates a complete Agent project from an agent.yaml configuration file.

Usage:
    python scripts/generate.py agent.yaml ./output_dir

This script maps the configuration in agent.yaml to each layer's code:
    L1 → app/l1_llm/factory.py
    L2 → app/l2_interface/chat_interface.py
    L3 → app/l3_prompt/system_prompts.py
    L4 → app/l4_agent/graph.py
    L5 → app/l5_tools/registry.py + base_tools.py
    L6 → app/l6_memory/
    L7 → app/l7_orchestrator/
    L8 → app/l8_api/routes/
    L9 → frontend/src/
    L10 → docker-compose.yml, .env, Dockerfile
"""

import os
import sys
import re
import shutil
import yaml
from pathlib import Path
from typing import Any, Optional


FRAMEWORKS = [
    "langgraph",
    "openai-agents",
    "claude-sdk",
    "adk",
    "autogen",
    "bare",
]


def _interactive_framework_select() -> str:
    """Interactive framework selection (M0.21) — never defaults silently.
    Prints the selection map from docs/framework-selection.md and asks the user.
    """
    print("")
    print("=== 框架选型（不默认绑定，请选择 Agent 运行时框架） ===")
    print("  1) langgraph      - LangGraph 1.0（生产级复杂编排/状态机/checkpoint 恢复）")
    print("  2) openai-agents  - OpenAI Agents SDK（轻量交接制/Guardrails）")
    print("  3) claude-sdk     - Claude Agent SDK（工具循环/子 Agent/生命周期钩子）")
    print("  4) adk            - Google ADK（Gemini 生态/A2A 原生）")
    print("  5) autogen        - AutoGen/AG2（多角色讨论/群体智能）")
    print("  6) bare           - 自研核心（零依赖 while-loop，完全自主可控）")
    print("  0) 查看完整全景矩阵（docs/framework-selection.md）后重新选择")
    while True:
        choice = input("请输入编号 [1-6]: ").strip()
        if choice == "0":
            print("请打开 docs/framework-selection.md 查看六类框架全景与决策树，然后重新运行本命令。")
            sys.exit(0)
        if choice.isdigit() and 1 <= int(choice) <= 6:
            return FRAMEWORKS[int(choice) - 1]
        print("无效输入，请输入 1-6")


# ============================================================
# Template paths
# ============================================================
TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates"

# ============================================================
# Utility functions
# ============================================================

def ensure_dir(path: str):
    """Ensure the directory exists"""
    os.makedirs(path, exist_ok=True)

def write_file(filepath: str, content: str):
    """Write a file"""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  ✓ Generated: {filepath}")

def copy_template(src: str, dst: str):
    """Copy a template file"""
    shutil.copy2(src, dst)
    print(f"  ✓ Copied: {src} → {dst}")

def load_config(config_path: str) -> dict:
    """Load YAML configuration"""
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)
    return config


# ============================================================
# Layer generators
# ============================================================

def generate_l1_llm(config: dict, output_dir: str):
    """Generate L1 LLM layer code"""
    llm_config = config.get("llm", {})
    provider = llm_config.get("provider", "openai")
    model = llm_config.get("model", "gpt-4o")
    temperature = llm_config.get("temperature", 0.7)
    max_tokens = llm_config.get("max_tokens", 4096)
    api_base = llm_config.get("api_base", "")

    # Generate system_prompts.py
    prompt_config = config.get("prompt", {})
    system_prompt = prompt_config.get("system_prompt", "你是一个智能助手。")
    write_file(
        f"{output_dir}/app/l3_prompt/system_prompts.py",
        f'''"""L3 - System prompt definitions (auto-generated by generate.py)"""

DEFAULT_SYSTEM_PROMPT = """{system_prompt}"""


def get_default_prompt() -> str:
    return DEFAULT_SYSTEM_PROMPT
'''.strip()
    )

    # Generate factory.py
    provider_imports = {
        "openai": "from .openai_adapter import OpenAIAdapter",
        "anthropic": "from .anthropic_adapter import AnthropicAdapter",
        "deepseek": "from .deepseek_adapter import DeepSeekAdapter",
        "ollama": "from .ollama_adapter import OllamaAdapter",
    }
    provider_create = {
        "openai": f'return OpenAIAdapter(model="{model}", temperature={temperature}, max_tokens={max_tokens})',
        "anthropic": f'return AnthropicAdapter(model="{model}", temperature={temperature}, max_tokens={max_tokens})',
        "deepseek": f'return DeepSeekAdapter(model="{model}", temperature={temperature}, max_tokens={max_tokens})',
        "ollama": f'return OllamaAdapter(model="{model}", temperature={temperature}, max_tokens={max_tokens})',
    }

    imports = provider_imports.get(provider, provider_imports["openai"])
    create = provider_create.get(provider, provider_create["openai"])

    if api_base:
        # Third-party compatible service with api_base
        imports = "from .openai_adapter import OpenAIAdapter"
        create = f'return OpenAIAdapter(model="{model}", api_base="{api_base}", temperature={temperature}, max_tokens={max_tokens})'

    write_file(
        f"{output_dir}/app/l1_llm/factory.py",
        f'''"""L1 - LLM factory method (auto-generated by generate.py)

Creates an LLM adapter instance based on configuration.
Provider: {provider}
Model: {model}
"""

{imports}
from .base import LLMAdapter


def create_llm() -> LLMAdapter:
    """Create an LLM adapter instance"""
    {create}
'''.strip()
    )

    # Generate l1_llm/__init__.py
    write_file(
        f"{output_dir}/app/l1_llm/__init__.py",
        '''"""L1 - LLM layer"""
from .base import LLMAdapter
from .factory import create_llm
'''.strip()
    )


def generate_l3_prompt(config: dict, output_dir: str):
    """Generate L3 prompt engineering layer code"""
    prompt_config = config.get("prompt", {})
    system_prompt = prompt_config.get("system_prompt", "你是一个智能助手。")
    role_template = prompt_config.get("role_template", "default")
    output_format = prompt_config.get("output_format", "text")

    write_file(
        f"{output_dir}/app/l3_prompt/role_templates.py",
        f'''"""L3 - Role templates (auto-generated by generate.py)"""

ROLE_TEMPLATES = {{
    "{role_template}": {{
        "system_prompt": """{system_prompt}""",
        "description": "Generated by {role_template} role template",
        "output_format": "{output_format}",
    }},
    "default": {{
        "system_prompt": "你是一个智能助手。请用简洁、准确的语言回答用户的问题。",
        "description": "Default role",
        "output_format": "text",
    }},
}}


def get_role_prompt(role_name: str) -> str | None:
    """Get the system prompt for a role template"""
    template = ROLE_TEMPLATES.get(role_name)
    if template:
        return template["system_prompt"]
    return None
'''.strip()
    )


def generate_l4_bare(config: dict, output_dir: str):
    """Generate a zero-dependency while-loop runtime (framework='bare').

    Reference implementation of the framework-agnostic AgentRuntime contract
    (docs/framework-selection.md 2.1): run / stream / bind_tools / checkpoint.
    No LangChain/LangGraph dependency — only the LLM adapter (L1) and
    ToolRegistry (L5), which are framework-agnostic.
    """
    graph_type = config.get("agent_framework", {}).get("graph_type", "single")
    max_iterations = config.get("agent_framework", {}).get("max_iterations", 10)
    write_file(
        f"{output_dir}/app/l4_agent/graph.py",
        f'''"""L4 - Bare while-loop runtime (framework='bare', framework-agnostic)

Zero-dependency ReAct loop implementing the AgentRuntime contract:
  run(messages, config) -> AgentResult
  stream(messages, config) -> AsyncIterator[AgentEvent]
  bind_tools(tools) / checkpoint(thread_id)

Graph type: {graph_type}
Max iterations: {max_iterations}
"""

from __future__ import annotations

import asyncio
import json
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, AsyncIterator, Callable, Optional


@dataclass
class AgentEvent:
    """Unified event stream (M3.18): agent_message / tool_call / tool_result / done"""
    type: str
    content: Any = None
    timestamp: float = field(default_factory=time.time)


@dataclass
class AgentResult:
    text: str
    tool_calls: list = field(default_factory=list)
    usage: dict = field(default_factory=dict)
    latency_ms: float = 0.0
    trace_id: str = field(default_factory=lambda: uuid.uuid4().hex)


class BareAgentRuntime:
    """Minimal framework-agnostic runtime: while-loop ReAct with tools."""

    def __init__(self, llm_factory, tools: Optional[dict] = None, max_iterations: int = {max_iterations}):
        # LLM is created lazily so app startup never requires an API key
        # (LLMAdapter construction may validate credentials, e.g. OpenAI).
        self._llm_factory = llm_factory
        self._llm = None
        self.tools = tools or {{}}        # name -> callable (ToolRegistry, L5)
        self.max_iterations = max_iterations
        self._memory: dict[str, list] = {{}}   # thread_id -> messages
        self._tool_schemas = [
            {{"name": n, "description": getattr(t, "__doc__", "") or "", "parameters": {{}}}}
            for n, t in self.tools.items()
        ]

    def _get_llm(self):
        """Lazily build the LLM adapter on first use."""
        if self._llm is None:
            self._llm = self._llm_factory()
        return self._llm

    # ---- AgentRuntime contract ------------------------------------
    def bind_tools(self, tools: dict) -> None:
        self.tools.update(tools)

    def checkpoint(self, thread_id: str) -> "BareAgentRuntime":
        """Return a runtime bound to a thread's conversation history."""
        self._memory.setdefault(thread_id, [])
        return self

    async def run(self, messages: list, config: Optional[dict] = None) -> AgentResult:
        start = time.perf_counter()
        thread_id = (config or {{}}).get("thread_id", "default")
        history = self._memory.setdefault(thread_id, [])
        history.extend(messages)
        tool_calls_log: list = []

        for _ in range(self.max_iterations):
            resp = await self._get_llm().invoke(
                history, tools=self._tool_schemas or None
            )
            if getattr(resp, "tool_calls", None):
                for tc in resp.tool_calls:
                    tool_calls_log.append(tc)
                    fn = self.tools.get(tc.get("name"))
                    if fn is None:
                        result = f"Error: unknown tool {{tc.get('name')}}"
                    else:
                        try:
                            result = await fn(**tc.get("arguments", {{}}))
                        except Exception as e:  # noqa: BLE001
                            result = f"Tool error: {{e}}"
                    history.append({{"role": "tool", "content": str(result), "tool_call_id": tc.get("id")}})
                continue
            text = getattr(resp, "content", "") or ""
            history.append({{"role": "assistant", "content": text}})
            return AgentResult(
                text=text,
                tool_calls=tool_calls_log,
                usage=getattr(resp, "usage", {{}}) or {{}},
                latency_ms=(time.perf_counter() - start) * 1000,
            )

        return AgentResult(
            text="Reached max_iterations without a final answer.",
            tool_calls=tool_calls_log,
            latency_ms=(time.perf_counter() - start) * 1000,
        )

    async def ainvoke(self, inputs: dict, config: Optional[dict] = None) -> dict:
        """LangGraph-style ainvoke compatibility (used by L7 orchestrator / A2A)."""
        messages = []
        for m in inputs.get("messages", []):
            if isinstance(m, tuple):
                messages.append({{"role": m[0], "content": m[1]}})
            elif isinstance(m, dict):
                messages.append(m)
            else:
                messages.append({{"role": "user", "content": str(m)}})
        result = await self.run(messages, config)
        thread_id = (config or {{}}).get("thread_id", "default")
        history = self._memory.setdefault(thread_id, [])
        return {{"messages": history, "agent_result": result}}

    async def stream(self, messages: list, config: Optional[dict] = None) -> AsyncIterator[AgentEvent]:
        """Emit fine-grained events: agent_message / tool_call / tool_result / done (M3.18)."""
        start = time.perf_counter()
        thread_id = (config or {{}}).get("thread_id", "default")
        history = self._memory.setdefault(thread_id, [])
        history.extend(messages)
        tool_calls_log: list = []

        for _ in range(self.max_iterations):
            resp = await self._get_llm().invoke(history, tools=self._tool_schemas or None)
            if getattr(resp, "tool_calls", None):
                for tc in resp.tool_calls:
                    tool_calls_log.append(tc)
                    yield AgentEvent("tool_call", {{"name": tc.get("name"), "input": tc.get("arguments", {{}})}})
                    fn = self.tools.get(tc.get("name"))
                    if fn is None:
                        result = f"Error: unknown tool {{tc.get('name')}}"
                    else:
                        try:
                            result = await fn(**tc.get("arguments", {{}}))
                        except Exception as e:  # noqa: BLE001
                            result = f"Tool error: {{e}}"
                    history.append({{"role": "tool", "content": str(result), "tool_call_id": tc.get("id")}})
                    yield AgentEvent("tool_result", {{"name": tc.get("name"), "output": str(result)[:500]}})
                continue
            text = getattr(resp, "content", "") or ""
            history.append({{"role": "assistant", "content": text}})
            yield AgentEvent("agent_message", text)
            yield AgentEvent(
                "done",
                {{
                    "usage": getattr(resp, "usage", {{}}) or {{}},
                    "latency_ms": (time.perf_counter() - start) * 1000,
                    "tool_calls": tool_calls_log,
                }},
            )
            return

        yield AgentEvent(
            "done",
            {{"usage": {{}}, "latency_ms": (time.perf_counter() - start) * 1000, "tool_calls": tool_calls_log}},
        )


# ── Module-level compatibility layer (same names as the LangGraph variant) ──
# Used by L8 routes (chat.py / a2a.py), L7 orchestrator and app/main.py.

_runtime: Optional["BareAgentRuntime"] = None


def get_graph() -> "BareAgentRuntime":
    """Return the app-wide runtime singleton (LangGraph get_graph() compatible)."""
    global _runtime
    if _runtime is None:
        _runtime = build_single_agent_graph()
    return _runtime


def get_graph_config(thread_id: str) -> dict:
    """Build a run config for a thread (LangGraph get_graph_config() compatible)."""
    return {{"thread_id": thread_id}}


def build_single_agent_graph() -> "BareAgentRuntime":
    """Compatibility factory: same name as the LangGraph variant."""
    from app.l1_llm.factory import create_llm
    from app.l5_tools.registry import get_registry
    from app.l10_infra.config import settings

    def _llm_factory():
        return create_llm(
            provider=settings.LLM_PROVIDER,
            model=settings.LLM_MODEL,
            api_key=settings.LLM_API_KEY or None,
            api_base=settings.LLM_API_BASE or None,
            temperature=settings.LLM_TEMPERATURE,
            max_tokens=settings.LLM_MAX_TOKENS,
        )

    registry = get_registry()
    return BareAgentRuntime(llm_factory=_llm_factory, tools=registry.get_callables())
'''.strip()
    )


def generate_l4_agent(config: dict, output_dir: str):
    """Generate L4 Agent framework layer code

    Framework-agnostic (M0.21): reads config['framework'] (set in main() from
    --framework flag / agent.yaml field / interactive prompt).
      - 'bare'        -> self-contained while-loop runtime, zero framework deps
      - 'langgraph'   -> LangGraph 1.0 StateGraph (default reference impl)
      - others        -> adapter TODO comment (docs/framework-selection.md)
    """
    framework = config.get("framework") or config.get("agent_framework", {}).get("name", "langgraph")
    graph_type = config.get("agent_framework", {}).get("graph_type", "single")
    max_iterations = config.get("agent_framework", {}).get("max_iterations", 10)

    if framework == "bare":
        generate_l4_bare(config, output_dir)
        return

    orchestrator = config.get("orchestration", {})
    orchestration_mode = orchestrator.get("mode", "single")

    if graph_type == "single" or orchestration_mode == "single" or not orchestrator.get("agents"):
        # Single Agent graph
        # (also the fallback when a "supervisor"/multi-mode config declares no
        #  sub-agents — otherwise the emitted supervisor graph has an empty
        #  route map and is a syntax error)
        # Optional thinking layer (universal-agent): agent_framework.plan adds a
        # planner step before acting; agent_framework.reflect self-critiques the
        # final answer. Both default OFF to keep the baseline loop lean.
        enable_plan = bool(config.get("agent_framework", {}).get("plan", False))
        enable_reflect = bool(config.get("agent_framework", {}).get("reflect", False))
        extra_nodes = ""
        if enable_plan:
            extra_nodes += ", planner_node"
        if enable_reflect:
            extra_nodes += ", reflect_node"
        route_end = '"reflect"' if enable_reflect else "END"
        start_edges = (
            '    workflow.add_node("planner", planner_node)\n'
            '    workflow.add_edge(START, "planner")\n'
            '    workflow.add_edge("planner", "agent")\n'
        ) if enable_plan else '    workflow.add_edge(START, "agent")\n'
        reflect_block = (
            '    workflow.add_node("reflect", reflect_node)\n'
            '    workflow.add_edge("reflect", END)\n'
        ) if enable_reflect else ""
        reflect_map = ' "reflect": "reflect",' if enable_reflect else ""

        write_file(
            f"{output_dir}/app/l4_agent/graph.py",
            f'''"""L4 - Agent graph definition (auto-generated by generate.py)

Graph type: {graph_type}
Max iterations: {max_iterations}
Plan: {enable_plan} | Reflect: {enable_reflect}
"""

from typing import Optional
from langgraph.graph import StateGraph, START, END
from langgraph.types import Command
from langgraph.checkpoint.memory import MemorySaver

from .state import AgentState
from .nodes import agent_node, tool_node{extra_nodes}


def _route_from_agent(state: AgentState) -> str:
    """Route from the Agent node: tool call -> tools, otherwise reflect/END"""
    last_message = state["messages"][-1] if state.get("messages") else None
    if last_message and hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"
    return {route_end}


def build_single_agent_graph() -> StateGraph:
    """Build a single Agent graph (LangGraph v1.0 pattern)"""
    workflow = StateGraph(AgentState)
    workflow.add_node("agent", agent_node)
    workflow.add_node("tools", tool_node)
{start_edges}    workflow.add_conditional_edges(
        "agent",
        _route_from_agent,
        {{
            "tools": "tools",{reflect_map}
            END: END,
        }},
    )
    workflow.add_edge("tools", "agent")
{reflect_block}    return workflow


def compile_graph(graph: StateGraph, cache: Optional[str] = None) -> StateGraph:
    """Compile the graph, adding checkpoint (memory) support

    Args:
        graph: StateGraph to compile
        cache: Node cache strategy ("inmemory" or None)
    """
    checkpointer = MemorySaver()
    compile_kwargs = {{"checkpointer": checkpointer}}
    if cache:
        compile_kwargs["cache"] = cache
    return graph.compile(**compile_kwargs)


_graph = None


def get_graph() -> StateGraph:
    """Get the global graph instance"""
    global _graph
    if _graph is None:
        graph = build_single_agent_graph()
        _graph = compile_graph(graph)
    return _graph


def get_graph_config(thread_id: Optional[str] = None) -> dict:
    """Get the graph configuration"""
    return {{
        "configurable": {{
            "thread_id": thread_id or 'default',
            "max_tool_calls": 10,
        }},
    }}
'''.strip()
        )
    else:
        # Multi-Agent graph
        agents = orchestrator.get("agents", [])
        # 'aggregator' is the supervisor-pattern aggregation SINK, added once
        # by the hardcoded template below. Exclude it from the routable
        # sub-agent list so it is never added as a node twice (fixes
        # "ValueError: Node `aggregator` already present").
        seen = set()
        agent_names = []
        for a in agents:
            n = a.get("name", "agent")
            if n and n != "aggregator" and n not in seen:
                seen.add(n)
                agent_names.append(n)
        sub_agent_nodes = "".join('    workflow.add_node("%s", agent_node)\n' % name for name in agent_names)
        sub_agent_route_map = ", ".join('"%s": "%s"' % (n, n) for n in agent_names)
        sub_agent_list = ", ".join('"%s"' % n for n in agent_names)

        # Build intent->specialist routing rules from the real sub-agent
        # names (fix: previously the router returned hardcoded
        # "specialist_1/specialist_2" which are not real nodes, breaking
        # graph validation with "Found edge ending at unknown node").
        default_target = agent_names[0] if agent_names else "aggregator"
        route_rule_lines = []
        for a in agents:
            nm = a.get("name", "")
            if nm != "aggregator" and nm in agent_names:
                role = (a.get("role") or "") + " " + (a.get("system_prompt") or "")
                tokens = re.split(r'[^0-9A-Za-z\u4e00-\u9fff]+', nm + " " + role)
                stop = {"the", "for", "and", "with", "you", "your", "are", "to", "of", "in"}
                seen_kw = set()
                kws = []
                for t in tokens:
                    t = t.lower()
                    if len(t) >= 2 and t not in stop and t not in seen_kw:
                        seen_kw.add(t)
                        kws.append(t)
                if kws:
                    route_rule_lines.append('    ("%s", [%s]),' % (nm, ", ".join('"%s"' % k for k in kws)))
        route_rules = "\n".join(route_rule_lines) if route_rule_lines else "    # (no keyword rules; default routing)"

        write_file(
            f"{output_dir}/app/l4_agent/graph.py",
            f'''"""L4 - Agent graph definition (auto-generated by generate.py)

Graph type: {graph_type}
Sub-agents: {', '.join(agent_names)}
"""

from typing import Optional
from langgraph.graph import StateGraph, START, END
from langgraph.types import Command
from langgraph.checkpoint.memory import MemorySaver

from .state import AgentState
from .nodes import agent_node, tool_node, supervisor_node


def _route_to_specialist(state: AgentState) -> str:
    """Route to a specialist Agent based on user intent keywords"""
    last_message = state["messages"][-1].content.lower() if state.get("messages") else ""

    rules = [
{route_rules}
    ]

    for name, kws in rules:
        if any(kw in last_message for kw in kws):
            return name

    return "{default_target}"


def _route_from_specialist(state: AgentState) -> str:
    """Route from a specialist sub-agent: tool call -> tools, otherwise aggregate"""
    last_message = state["messages"][-1] if state.get("messages") else None
    if last_message and hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"
    return "aggregator"


def build_supervisor_graph() -> StateGraph:
    """Build a Supervisor orchestration graph (langgraph-supervisor pattern)"""
    workflow = StateGraph(AgentState)

    workflow.add_node("supervisor", supervisor_node)
{sub_agent_nodes}
    workflow.add_node("aggregator", agent_node)
    workflow.add_node("tools", tool_node)

    workflow.add_edge(START, "supervisor")

    workflow.add_conditional_edges(
        "supervisor",
        _route_to_specialist,
        {{
            {sub_agent_route_map},
            END: END,
        }},
    )

    for name in [{sub_agent_list}]:
        workflow.add_conditional_edges(
            name,
            _route_from_specialist,
            {{
                "tools": "tools",
                "aggregator": "aggregator",
            }},
        )

    workflow.add_edge("tools", "supervisor")
    workflow.add_edge("aggregator", END)
    return workflow


def compile_graph(graph: StateGraph, cache: Optional[str] = None) -> StateGraph:
    """Compile the graph, adding checkpoint (memory) support

    Args:
        graph: StateGraph to compile
        cache: Node cache strategy ("inmemory" or None)
    """
    checkpointer = MemorySaver()
    compile_kwargs = {{"checkpointer": checkpointer}}
    if cache:
        compile_kwargs["cache"] = cache
    return graph.compile(**compile_kwargs)


_graph = None


def get_graph() -> StateGraph:
    """Get the global graph instance"""
    global _graph
    if _graph is None:
        graph = build_supervisor_graph()
        _graph = compile_graph(graph)
    return _graph


def get_graph_config(thread_id: Optional[str] = None) -> dict:
    """Get the graph configuration"""
    return {{
        "configurable": {{
            "thread_id": thread_id or 'default',
            "max_tool_calls": 10,
        }},
    }}
'''.strip()
        )


def generate_l5_tools(config: dict, output_dir: str):
    """Generate L5 tool execution layer code"""
    tools_config = config.get("tools", {})
    enabled_tools = tools_config.get("enabled", [])
    custom_tools = tools_config.get("custom", [])

    # Generate base_tools.py - only includes enabled tools.
    #
    # (P0-1 fix) Every name that can appear in `enabled` must have a real
    # implementation below, otherwise the emitted BASE_TOOLS list would
    # reference an undefined symbol and the generated project would fail to
    # import. The following is the set of generic (universal-agent) base
    # capabilities — web, code execution, file I/O and data analysis — all
    # stdlib-only so the generated project needs no extra dependencies.
    tool_definitions = []

    base_impls = {
        "web_search": r'''
@tool
async def web_search(query: str) -> str:
    """Search the web for the latest information"""
    import httpx
    url = "https://api.duckduckgo.com/"
    params = {"q": query, "format": "json", "no_html": 1, "skip_disambig": 1}
    async with httpx.AsyncClient() as client:
        try:
            resp = await client.get(url, params=params, timeout=10.0)
            data = resp.json()
            results = []
            if data.get("Abstract"):
                results.append(f"摘要: {data['Abstract']}")
            for topic in data.get("RelatedTopics", [])[:5]:
                if isinstance(topic, dict) and "Text" in topic:
                    results.append(topic["Text"])
            return "\n".join(results) if results else "未找到相关结果"
        except Exception as e:
            return f"搜索失败: {str(e)}"
''',
        "web_fetch": r'''
@tool
async def web_fetch(url: str) -> str:
    """Fetch web page content"""
    import httpx, re
    async with httpx.AsyncClient() as client:
        try:
            resp = await client.get(url, timeout=15.0, follow_redirects=True)
            resp.encoding = resp.charset or "utf-8"
            text = resp.text
            text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.DOTALL)
            text = re.sub(r'<style[^>]*>.*?</style>', '', text, flags=re.DOTALL)
            text = re.sub(r'<[^>]+>', ' ', text)
            text = re.sub(r'\s+', ' ', text).strip()
            return text[:5000]
        except Exception as e:
            return f"获取页面失败: {str(e)}"
''',
        "current_time": r'''
@tool
async def current_time() -> str:
    """Get the current date and time"""
    from datetime import datetime
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
''',
        "calculate": r'''
@tool
async def calculate(expression: str) -> str:
    """Perform mathematical calculations"""
    allowed = set("0123456789.+-*/()% ")
    if not all(c in allowed for c in expression):
        return "错误: 表达式包含非法字符"
    try:
        result = eval(expression, {"__builtins__": {}}, {})
        return str(result)
    except Exception as e:
        return f"计算错误: {str(e)}"
''',
        "code_execute": r'''
@tool
async def code_execute(language: str, code: str, timeout: str = "30") -> str:
    """Execute code in an isolated subprocess (python/python3/sh/bash) and return output"""
    import subprocess, sys
    timeout_s = min(float(timeout or 30), 60)
    cmds = {
        "python": [sys.executable, "-c", code],
        "python3": [sys.executable, "-c", code],
        "sh": ["/bin/sh", "-c", code],
        "bash": ["/bin/bash", "-c", code],
    }
    cmd = cmds.get((language or "").lower())
    if cmd is None:
        return f"错误: 不支持的语言 '{language}'（支持 python/python3/sh/bash）"
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout_s,
            env={"PATH": "/usr/bin:/bin", "HOME": "/tmp"},
        )
        out = (proc.stdout or "")[-20000:]
        err = (proc.stderr or "")[-20000:]
        if proc.returncode != 0:
            return f"执行失败 (code={proc.returncode}):\n{err}"
        return out if out else "(无输出)"
    except subprocess.TimeoutExpired:
        return f"错误: 执行超时（>{timeout_s}s）"
    except Exception as e:
        return f"执行错误: {str(e)}"
''',
        "run_code": r'''
@tool
async def run_code(language: str, code: str, timeout: str = "30") -> str:
    """Execute code in an isolated subprocess (alias of code_execute)"""
    import subprocess, sys
    timeout_s = min(float(timeout or 30), 60)
    cmds = {
        "python": [sys.executable, "-c", code],
        "python3": [sys.executable, "-c", code],
        "sh": ["/bin/sh", "-c", code],
        "bash": ["/bin/bash", "-c", code],
    }
    cmd = cmds.get((language or "").lower())
    if cmd is None:
        return f"错误: 不支持的语言 '{language}'（支持 python/python3/sh/bash）"
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout_s,
            env={"PATH": "/usr/bin:/bin", "HOME": "/tmp"},
        )
        out = (proc.stdout or "")[-20000:]
        err = (proc.stderr or "")[-20000:]
        if proc.returncode != 0:
            return f"执行失败 (code={proc.returncode}):\n{err}"
        return out if out else "(无输出)"
    except subprocess.TimeoutExpired:
        return f"错误: 执行超时（>{timeout_s}s）"
    except Exception as e:
        return f"执行错误: {str(e)}"
''',
        "file_read": r'''
@tool
async def file_read(path: str) -> str:
    """Read a text file and return its content (max 50KB)"""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read(50000)
    except Exception as e:
        return f"读取失败: {str(e)}"
''',
        "file_write": r'''
@tool
async def file_write(path: str, content: str) -> str:
    """Write text content to a file (creates parent directories)"""
    import os
    try:
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return f"已写入 {len(content)} 字符到 {path}"
    except Exception as e:
        return f"写入失败: {str(e)}"
''',
        "read_csv": r'''
@tool
async def read_csv(path: str, max_rows: str = "50") -> str:
    """Read a CSV file and return its header plus the first N rows"""
    import csv
    try:
        rows = []
        with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:
            limit = max(int(max_rows or 50), 1)
            for i, row in enumerate(csv.reader(f)):
                if i >= limit:
                    break
                rows.append(row)
        if not rows:
            return "文件为空或无内容"
        lines = ["\t".join(str(c) for c in rows[0])]
        for row in rows[1:]:
            lines.append("\t".join(str(c) for c in row))
        return "\n".join(lines)
    except Exception as e:
        return f"读取CSV失败: {str(e)}"
''',
        "analyze_data": r'''
@tool
async def analyze_data(path: str) -> str:
    """Compute basic descriptive statistics for numeric columns of a CSV file"""
    import csv
    from collections import defaultdict
    try:
        rows = []
        with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:
            for row in csv.reader(f):
                rows.append(row)
        if len(rows) < 2:
            return "数据不足（需至少表头 + 1 行数据）"
        header = rows[0]
        cols = defaultdict(list)
        for row in rows[1:]:
            for i, h in enumerate(header):
                if i < len(row):
                    try:
                        cols[h].append(float(row[i]))
                    except (ValueError, TypeError):
                        cols[h].append(None)
        lines = [f"行数: {len(rows) - 1}", f"列数: {len(header)}"]
        for h in header:
            vals = [v for v in cols[h] if v is not None]
            if vals:
                avg = sum(vals) / len(vals)
                lines.append(f"  {h}: 非空={len(vals)} 均值={avg:.4f} 最小={min(vals):.4f} 最大={max(vals):.4f}")
            else:
                lines.append(f"  {h}: (非数值/空)")
        return "\n".join(lines)
    except Exception as e:
        return f"分析失败: {str(e)}"
''',
        "generate_chart": r'''
@tool
async def generate_chart(path: str, column: str = "") -> str:
    """Generate a lightweight ASCII bar chart for a numeric column of a CSV file"""
    import csv
    try:
        rows = []
        with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:
            for row in csv.reader(f):
                rows.append(row)
        if len(rows) < 2:
            return "数据不足（需至少表头 + 1 行数据）"
        header = rows[0]
        col = column if column else (header[0] if header else "")
        if col not in header:
            return f"未找到列 '{col}'，可用列: {', '.join(header)}"
        idx = header.index(col)
        values = []
        for row in rows[1:]:
            if idx < len(row):
                try:
                    values.append(float(row[idx]))
                except (ValueError, TypeError):
                    pass
        if not values:
            return f"列 '{col}' 无数值数据"
        n = min(len(values), 40)
        sample = values[-n:]
        vmin, vmax = min(sample), max(sample)
        span = (vmax - vmin) or 1.0
        width = 40
        lines = [f"ASCII 柱状图: {col}（最后 {n} 条）"]
        for i, v in enumerate(sample):
            bar = "#" * int((v - vmin) / span * width)
            lines.append(f"{i + 1:>3} | {v:>10.4f} | {bar}")
        return "\n".join(lines)
    except Exception as e:
        return f"生成图表失败: {str(e)}"
''',
    }

    # Custom tools
    custom_tool_defs = []
    for ct in custom_tools:
        name = ct.get("name", "custom_tool")
        desc = ct.get("description", "Custom tool")
        params = ct.get("parameters", {})
        param_docs = chr(10).join("        %s: %s" % (k, v.get('description', '')) for k, v in params.items())
        # Parameter declarations with defaults + inline validation (non-empty)
        param_parts = []
        param_validations = []
        for k, v in params.items():
            req = v.get('required', True) if isinstance(v, dict) else True
            decl = "%s: str" % k if req else "%s: str = \"\"" % k
            param_parts.append(decl)
            param_validations.append(
                "    if not %s:\n        return \"错误: 参数 %s 不能为空\"" % (k, k)
            )
        param_str = ", ".join(param_parts)
        validation_str = chr(10).join(param_validations)
        # Build the input dict literal outside the f-string (no backslashes allowed inside f-string expr)
        input_items = []
        for k in params.keys():
            input_items.append('        "%s": str(%s),' % (k, k))
        input_literal = chr(10).join(input_items)

        custom_tool_defs.append(f'''
@tool
async def {name}({param_str}) -> str:
    """{desc}

    {param_docs}
    """
    # ---- 参数校验（自动生成） ----
{validation_str}

    # ---- 业务逻辑（TODO: 在此实现真实逻辑） ----
    import json
    result = {{
{input_literal}
        "tool": "{name}",
        "message": "已接收参数",
    }}
    return json.dumps(result, ensure_ascii=False)
''')

    # (P0-1 fix) Only reference tools that are actually defined:
    #   * enabled  AND  * have a base implementation  AND  * not overridden
    #   by a custom tool of the same name (custom implementation wins).
    custom_names = {ct.get("name") for ct in custom_tools}
    base_names = []
    for t in enabled_tools:
        if t in custom_names:
            continue  # custom tool takes precedence
        if t in base_impls:
            tool_definitions.append(base_impls[t])
            base_names.append(t)
        else:
            print(f"  [!] 警告: enabled 工具 '{t}' 无生成实现，已跳过（避免未定义符号）")

    # Base tools list
    base_tools_list = "\n    ".join("%s," % n for n in base_names) if base_names else "# No base tools"

    # Custom tools list
    custom_tools_list = "\n    ".join("%s," % ct.get("name", "custom_tool") for ct in custom_tools) if custom_tools else "# No custom tools"

    write_file(
        f"{output_dir}/app/l5_tools/base_tools.py",
        f'''"""L5 - Base tool definitions (auto-generated by generate.py)

Enabled tools: {', '.join(enabled_tools) if enabled_tools else 'none'}
Registered base tools: {', '.join(base_names) if base_names else 'none'}
"""

from langchain_core.tools import tool

{''.join(tool_definitions)}

# Base tools list
BASE_TOOLS = [
    {base_tools_list}
]
'''.strip()
    )

    # Generate custom_tools.py
    write_file(
        f"{output_dir}/app/l5_tools/custom_tools.py",
        f'''"""L5 - Custom tools (auto-generated by generate.py)

Custom tools: {', '.join(ct.get('name', 'custom_tool') for ct in custom_tools) if custom_tools else 'none'}
"""

from langchain_core.tools import tool

{''.join(custom_tool_defs)}

# Custom tools list
CUSTOM_TOOLS = [
    {custom_tools_list}
]
'''.strip()
    )


def generate_l8_api(config: dict, output_dir: str):
    """Generate L8 API service layer code"""
    api_config = config.get("api", {})
    auth_enabled = api_config.get("auth_enabled", False)
    cors_origins = api_config.get("cors_origins", ["http://localhost:5173"])
    ui_config = config.get("ui", {})
    agent_name = config.get("agent", {}).get("name", "Agent")

    # Generate main.py
    write_file(
        f"{output_dir}/app/main.py",
        f'''"""L8+L10 - Application entry (auto-generated by generate.py)
Application name: {agent_name}
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .l8_api.routes.chat import router as chat_router
from .l8_api.routes.health import router as health_router
from .l8_api.routes.config import router as config_router
from .l8_api.routes.sessions import router as sessions_router
from .l8_api.routes.tools import router as tools_router
from .l8_api.routes.a2a import router as a2a_router
from .l8_api.routes.a2a import api_router as a2a_api_router
from .l8_api.routes.voice import router as voice_router
from .l8_api.routes.nlp import router as nlp_router
from .l8_api.routes.security import router as security_router
from .l8_api.routes.admin import router as admin_router
from .l8_api.routes.tasks import router as tasks_router
from .l8_api.routes.workspaces import router as workspaces_router
from .l8_api.routes.skills import router as skills_router
from .l8_api.routes.notifications import router as notifications_router
from .l8_api.routes.canvas import router as canvas_router
from .l8_api.routes.sandbox import router as sandbox_router
from .l5_tools.registry import ToolRegistry
from .l5_tools.base_tools import BASE_TOOLS
from .l5_tools.custom_tools import CUSTOM_TOOLS
from .l10_infra.config import settings


def create_app() -> FastAPI:
    """Create and configure the FastAPI application"""
    app = FastAPI(
        title="{agent_name}",
        version="1.0.0",
        description="Agent application automatically generated by Agent Builder",
    )

    # CORS
    app.add_middleware(
        CORSMiddleware,
        allow_origins={cors_origins},
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Routes
    app.include_router(health_router, prefix="/api", tags=["health"])
    app.include_router(chat_router, prefix="/api", tags=["chat"])
    app.include_router(config_router, prefix="/api", tags=["config"])
    app.include_router(sessions_router, prefix="/api", tags=["sessions"])
    app.include_router(tools_router, prefix="/api", tags=["tools"])
    app.include_router(a2a_router, prefix="", tags=["a2a"])
    app.include_router(a2a_api_router, prefix="/api", tags=["a2a"])
    app.include_router(voice_router, prefix="/api", tags=["voice"])
    app.include_router(nlp_router, prefix="/api", tags=["nlp"])
    app.include_router(security_router, prefix="/api", tags=["security"])
    app.include_router(admin_router, prefix="/api", tags=["admin"])
    app.include_router(tasks_router, prefix="/api", tags=["tasks"])
    app.include_router(workspaces_router, prefix="/api", tags=["workspaces"])
    app.include_router(skills_router, prefix="/api", tags=["skills"])
    app.include_router(notifications_router, prefix="/api", tags=["notifications"])
    app.include_router(canvas_router, prefix="/api", tags=["canvas"])
    app.include_router(sandbox_router, prefix="/api", tags=["sandbox"])

    @app.on_event("startup")
    async def startup():
        """Initialize each layer"""
        # L5: Register tools
        for tool in BASE_TOOLS:
            ToolRegistry.register(tool, category="general")
        for tool in CUSTOM_TOOLS:
            ToolRegistry.register(tool, category="custom")
        print(f"  ✓ Registered {{len(ToolRegistry.get_all())}} tools")

        # L4: Initialize the Agent graph
        from .l4_agent.graph import get_graph
        graph = get_graph()
        print(f"  ✓ Agent graph initialized (LLM: {{settings.LLM_PROVIDER}}/{{settings.LLM_MODEL}})")

    @app.on_event("shutdown")
    async def shutdown():
        ToolRegistry.clear()

    return app


app = create_app()


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True)
'''.strip()
    )

    # Generate config.py (L10)
    llm_config = config.get("llm", {})
    write_file(
        f"{output_dir}/app/l10_infra/config.py",
        f'''"""L10 - Configuration management (auto-generated by generate.py)"""

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application global configuration"""

    # Application info
    APP_NAME: str = "{agent_name}"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False

    # CORS
    CORS_ORIGINS: list[str] = {cors_origins}

    # L1: LLM configuration
    LLM_PROVIDER: str = "{llm_config.get("provider", "openai")}"
    LLM_MODEL: str = "{llm_config.get("model", "gpt-4o")}"
    LLM_API_KEY: str = ""
    LLM_API_BASE: str = "{llm_config.get("api_base", "")}"
    LLM_TEMPERATURE: float = {llm_config.get("temperature", 0.7)}
    LLM_MAX_TOKENS: int = {llm_config.get("max_tokens", 4096)}

    # L2: Model interface configuration
    LLM_RETRY_COUNT: int = 3
    LLM_RETRY_DELAY: float = 1.0
    MODEL_FALLBACK_ENABLED: bool = False

    # L5: Tool configuration
    MAX_TOOL_CALLS: int = 10
    TOOL_TIMEOUT: int = 30

    # L6: Memory configuration
    MEMORY_TYPE: str = "{config.get("memory", {}).get("type", "buffer")}"
    MEMORY_MAX_MESSAGES: int = {config.get("memory", {}).get("max_messages", 50)}

    # L8: API configuration
    API_KEY: str = ""
    RATE_LIMIT: int = 60

    # L10: AI security enforcement (deep-spec 27)
    SECURITY_ENABLED: bool = True
    SECURITY_BLOCK_ACTION: str = "block"

    # L10: Infrastructure
    LOG_LEVEL: str = "{config.get("deployment", {}).get("log_level", "INFO")}"

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


settings = Settings()
'''.strip()
    )


def generate_l10_infra(config: dict, output_dir: str):
    """Generate L10 infrastructure layer code"""
    deployment = config.get("deployment", {})
    deploy_type = deployment.get("type", "docker")
    agent_config = config.get("agent", {})
    agent_name = agent_config.get("name", "agent")
    llm_config = config.get("llm", {})

    # Generate .env.example
    write_file(
        f"{output_dir}/.env.example",
        f"""# ============================================================
# {agent_name} Environment variable configuration
# Copy this file to .env and fill in actual values
# ============================================================

# L1: LLM configuration
LLM_PROVIDER={llm_config.get("provider", "openai")}
LLM_MODEL={llm_config.get("model", "gpt-4o")}
LLM_API_KEY=your-api-key-here
LLM_API_BASE=
LLM_TEMPERATURE={llm_config.get("temperature", 0.7)}
LLM_MAX_TOKENS={llm_config.get("max_tokens", 4096)}

# L2: Interface configuration
LLM_RETRY_COUNT=3
LLM_RETRY_DELAY=1.0

# L5: Tool configuration
MAX_TOOL_CALLS=10
TOOL_TIMEOUT=30

# L6: Memory configuration
MEMORY_TYPE={config.get("memory", {}).get("type", "buffer")}
MEMORY_MAX_MESSAGES={config.get("memory", {}).get("max_messages", 50)}

# L8: API configuration
API_KEY=

# L10: Logging
LOG_LEVEL=INFO
LOG_FORMAT=json
""".strip()
    )

    # Generate requirements.txt
    write_file(
        f"{output_dir}/requirements.txt",
        """# Python dependencies
fastapi>=0.115.0
uvicorn[standard]>=0.30.0
pydantic>=2.0.0
pydantic-settings>=2.5.0
langchain-core>=0.3.0
langgraph>=1.0.0
httpx>=0.27.0
pyyaml>=6.0
python-dotenv>=1.0.0
""".strip()
    )

    # Generate Dockerfile
    write_file(
        f"{output_dir}/Dockerfile",
        """FROM python:3.12-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy code
COPY . .

# Start
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
""".strip()
    )

    # Generate docker-compose.yml
    if deploy_type == "docker":
        write_file(
            f"{output_dir}/docker-compose.yml",
            f"""version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CORS_ORIGINS=["http://localhost:5173","http://localhost:3000"]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://localhost:8000/api
    restart: unless-stopped
""".strip()
        )

    # Generate start.sh
    write_file(
        f"{output_dir}/scripts/start.sh",
        """#!/bin/bash
# Startup script

echo "=== Starting Agent application ==="

# Check .env
if [ ! -f .env ]; then
    echo "⚠  .env file does not exist, copying from .env.example..."
    cp .env.example .env
    echo "⚠  Please edit the .env file and fill in your API Key"
    exit 1
fi

# Install dependencies
echo "Installing Python dependencies..."
pip install -r requirements.txt -q

# Start backend
echo "Starting backend service..."
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
""".strip()
    )
    os.chmod(f"{output_dir}/scripts/start.sh", 0o755)


def generate_frontend(config: dict, output_dir: str):
    """Generate L9 frontend code"""
    ui_config = config.get("ui", {})
    ui_type = ui_config.get("type", "chat")
    features = ui_config.get("features", [])
    agent_config = config.get("agent", {})
    agent_name = agent_config.get("name", "Agent")

    # Generate package.json
    write_file(
        f"{output_dir}/frontend/package.json",
        '''{
  "name": "agent-frontend",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.0",
    "react-dom": "^18.3.0",
    "react-markdown": "^9.0.0"
  },
  "devDependencies": {
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.0",
    "typescript": "^5.6.0",
    "vite": "^6.0.0"
  }
}
'''.strip()
    )

    # Generate index.html
    write_file(
        f"{output_dir}/frontend/index.html",
        '''<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>''' + agent_name + '''</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
'''.strip()
    )

    # Generate main.tsx
    write_file(
        f"{output_dir}/frontend/src/main.tsx",
        '''import React from 'react'
import ReactDOM from 'react-dom/client'
import { App } from './App'
import './styles/index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
'''.strip()
    )

    # Generate types/index.ts
    write_file(
        f"{output_dir}/frontend/src/types/index.ts",
        '''export interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: Date
  isStreaming?: boolean
  toolCalls?: ToolCallInfo[]
}

export interface ToolCallInfo {
  tool: string
  input: string
  output?: string
  status: 'running' | 'completed' | 'error'
  error?: string
}

export interface SSEEvent {
  type: 'token' | 'tool_start' | 'tool_end' | 'thinking' | 'done' | 'error' | 'node_start' | 'node_end'
  content?: string
  thread_id?: string
  tool_calls?: number
  tool?: string
  input?: string
  output?: string
  node?: string
}

export interface AgentConfig {
  name: string
  type: string
  description: string
  ui: {
    type: string
    title: string
    features: string[]
  }
}
'''.strip()
    )

    # Generate API client
    write_file(
        f"{output_dir}/frontend/src/l8_api/api.ts",
        '''import type { SSEEvent, AgentConfig } from '../types'

const API_BASE = '/api'

export async function* streamChat(
  message: string,
  threadId?: string
): AsyncGenerator<SSEEvent> {
  const response = await fetch(`${API_BASE}/chat`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ message, thread_id: threadId }),
  })

  if (!response.ok) {
    throw new Error(`Chat request failed: ${response.status}`)
  }

  const reader = response.body!.getReader()
  const decoder = new TextDecoder()
  let buffer = ''

  while (true) {
    const { done, value } = await reader.read()
    if (done) break

    buffer += decoder.decode(value, { stream: true })
    const lines = buffer.split(String.fromCharCode(10))
    buffer = lines.pop() || ''

    for (const line of lines) {
      const trimmed = line.trim()
      if (trimmed.startsWith('data: ')) {
        try {
          const data = JSON.parse(trimmed.slice(6)) as SSEEvent
          yield data
        } catch { /* skip malformed lines */ }
      }
    }
  }
}

export async function getAgentConfig(): Promise<AgentConfig> {
  const response = await fetch(`${API_BASE}/config`)
  if (!response.ok) {
    return {
      name: "''' + agent_name + '''",
      type: "''' + config.get("agent", {}).get("type", "chat") + '''",
      description: "''' + config.get("agent", {}).get("description", "") + '''",
      ui: {
        type: "''' + ui_type + '''",
        title: "''' + ui_config.get("title", agent_name) + '''",
        features: ''' + str(features) + ''',
      },
    }
  }
  return response.json()
}
'''.strip()
    )

    # Generate App.tsx
    features_str = str(features)
    agent_cfg = config.get('agent', {})
    agent_type_str = agent_cfg.get('type', 'chat')
    agent_desc_str = agent_cfg.get('description', '')
    write_file(
        f"{output_dir}/frontend/src/App.tsx",
        f'''import {{ useState, useEffect }} from 'react'
import {{ Header }} from './l9_ui/layout/Header'
import {{ Sidebar }} from './l9_ui/layout/Sidebar'
import {{ ChatWindow }} from './l9_ui/chat/ChatWindow'
import {{ ErrorBoundary }} from './l9_ui/shared/ErrorBoundary'
import {{ getAgentConfig }} from './l8_api/api'
import type {{ AgentConfig }} from './types'

export interface Session {{
  id: string
  title: string
  createdAt: Date
}}

export function App() {{
  const [sessions, setSessions] = useState<Session[]>([
    {{ id: 'default', title: 'New Chat', createdAt: new Date() }},
  ])
  const [activeSession, setActiveSession] = useState('default')
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [config, setConfig] = useState<AgentConfig | null>(null)

  useEffect(() => {{
    getAgentConfig().then(setConfig).catch(() => {{
      // If the API is unavailable, use default configuration
      setConfig({{
        name: "{agent_name}",
        type: "{agent_type_str}",
        description: "{agent_desc_str}",
        ui: {{ type: "{ui_type}", title: "{ui_config.get('title', agent_name)}", features: {features_str} }},
      }})
    }})
  }}, [])

  const features = config?.ui?.features || {features_str}
  const showToolViz = features.includes('tool_visualization')
  const showFileUpload = features.includes('file_upload')
  const showChartDisplay = features.includes('chart_display')

  const createSession = () => {{
    const id = crypto.randomUUID()
    setSessions(prev => [...prev, {{ id, title: `会话 ${{prev.length + 1}}`, createdAt: new Date() }}])
    setActiveSession(id)
  }}

  const deleteSession = (id: string) => {{
    setSessions(prev => prev.filter(s => s.id !== id))
    if (activeSession === id) {{
      setActiveSession(sessions[0]?.id || 'default')
    }}
  }}

  return (
    <ErrorBoundary>
      <div className="app-container">
        <Header
          onToggleSidebar={{() => setSidebarOpen(!sidebarOpen)}}
          sessionTitle={{sessions.find(s => s.id === activeSession)?.title || config?.ui?.title || '{agent_name}'}}
        />
        <div className="app-body">
          <Sidebar
            sessions={{sessions}}
            activeSession={{activeSession}}
            onSelect={{setActiveSession}}
            onCreate={{createSession}}
            onDelete={{deleteSession}}
            isOpen={{sidebarOpen}}
            onClose={{() => setSidebarOpen(false)}}
          />
          <main className="main-content">
            <ChatWindow
              key={{activeSession}}
              sessionId={{activeSession}}
              showToolViz={{showToolViz}}
              showFileUpload={{showFileUpload}}
              showChartDisplay={{showChartDisplay}}
            />
          </main>
        </div>
      </div>
    </ErrorBoundary>
  )
}}
'''.strip()
    )

    # Generate ChatWindow.tsx
    write_file(
        f"{output_dir}/frontend/src/l9_ui/chat/ChatWindow.tsx",
        '''import { useState, useRef, useEffect, useCallback } from 'react'
import { MessageBubble } from './MessageBubble'
import { ChatInput } from './ChatInput'
import { ToolCall } from './ToolCall'
import { streamChat } from '../../l8_api/api'
import type { Message, ToolCallInfo } from '../../types'

interface ChatWindowProps {
  sessionId: string
  showToolViz?: boolean
  showFileUpload?: boolean
  showChartDisplay?: boolean
}

export function ChatWindow({ sessionId: _sessionId, showToolViz = true, showFileUpload = false, showChartDisplay = false }: ChatWindowProps) {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome',
      role: 'assistant',
      content: '你好！我是智能助手。请告诉我你需要什么帮助？',
      timestamp: new Date(),
    },
  ])
  const [isLoading, setIsLoading] = useState(false)
  const [threadId, setThreadId] = useState<string | undefined>()
  const messagesEndRef = useRef<HTMLDivElement>(null)

  const scrollToBottom = useCallback(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [])

  useEffect(() => { scrollToBottom() }, [messages, scrollToBottom])

  const handleSend = async (content: string) => {
    const userMessage: Message = {
      id: crypto.randomUUID(), role: 'user', content, timestamp: new Date(),
    }
    setMessages(prev => [...prev, userMessage])
    setIsLoading(true)

    const assistantId = crypto.randomUUID()
    const assistantMessage: Message = {
      id: assistantId, role: 'assistant', content: '', timestamp: new Date(),
      isStreaming: true, toolCalls: [],
    }
    setMessages(prev => [...prev, assistantMessage])
    let currentToolCalls: ToolCallInfo[] = []

    try {
      for await (const event of streamChat(content, threadId)) {
        switch (event.type) {
          case 'token':
            setMessages(prev =>
              prev.map(m => m.id === assistantId ? { ...m, content: m.content + (event.content || '') } : m)
            )
            break
          case 'tool_start':
            if (showToolViz) {
              const toolCall: ToolCallInfo = { tool: event.tool || '', input: event.input || '', status: 'running' }
              currentToolCalls = [...currentToolCalls, toolCall]
              setMessages(prev =>
                prev.map(m => m.id === assistantId ? { ...m, toolCalls: [...currentToolCalls] } : m)
              )
            }
            break
          case 'tool_end':
            if (showToolViz) {
              currentToolCalls = currentToolCalls.map(tc =>
                tc.tool === event.tool ? { ...tc, output: event.output, status: 'completed' as const } : tc
              )
              setMessages(prev =>
                prev.map(m => m.id === assistantId ? { ...m, toolCalls: [...currentToolCalls] } : m)
              )
            }
            break
          case 'done':
            if (event.thread_id) setThreadId(event.thread_id)
            setMessages(prev =>
              prev.map(m => m.id === assistantId ? { ...m, isStreaming: false } : m)
            )
            setIsLoading(false)
            break
        }
      }
    } catch (error) {
      setMessages(prev =>
        prev.map(m => m.id === assistantId ? { ...m, content: m.content || `连接错误: ${error}`, isStreaming: false } : m)
      )
      setIsLoading(false)
    }
  }

  return (
    <div className="chat-window">
      <div className="messages-container">
        {messages.map(msg => (
          <div key={msg.id}>
            <MessageBubble message={msg} />
            {msg.toolCalls && msg.toolCalls.length > 0 && (
              <div className="tool-calls-container">
                {msg.toolCalls.map((tc, i) => <ToolCall key={i} info={tc} />)}
              </div>
            )}
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>
      <ChatInput onSend={handleSend} disabled={isLoading} showFileUpload={showFileUpload} />
    </div>
  )
}
'''.strip()
    )

    # Generate ChatInput.tsx
    write_file(
        f"{output_dir}/frontend/src/l9_ui/chat/ChatInput.tsx",
        '''import { useState, useRef } from 'react'

interface ChatInputProps {
  onSend: (message: string) => void
  disabled: boolean
  showFileUpload?: boolean
}

export function ChatInput({ onSend, disabled, showFileUpload = false }: ChatInputProps) {
  const [input, setInput] = useState('')
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  const handleSubmit = () => {
    const trimmed = input.trim()
    if (!trimmed || disabled) return
    onSend(trimmed)
    setInput('')
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto'
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSubmit()
    }
  }

  return (
    <div className="chat-input-container">
      {showFileUpload && (
        <button className="file-upload-btn" title="上传文件">
          📎
        </button>
      )}
      <textarea
        ref={textareaRef}
        className="chat-input"
        value={input}
        onChange={e => setInput(e.target.value)}
        onKeyDown={handleKeyDown}
        placeholder="输入消息，Enter 发送，Shift+Enter 换行"
        rows={1}
        disabled={disabled}
      />
      <button
        className="send-btn"
        onClick={handleSubmit}
        disabled={disabled || !input.trim()}
      >
        {disabled ? '⏳' : '发送'}
      </button>
    </div>
  )
}
'''.strip()
    )

    # Generate MessageBubble.tsx
    write_file(
        f"{output_dir}/frontend/src/l9_ui/chat/MessageBubble.tsx",
        '''import type { Message } from '../../types'

interface MessageBubbleProps {
  message: Message
}

export function MessageBubble({ message }: MessageBubbleProps) {
  const isUser = message.role === 'user'

  return (
    <div className={`message-bubble ${isUser ? 'user' : 'assistant'}`}>
      <div className="message-avatar">{isUser ? '👤' : '🤖'}</div>
      <div className="message-content">
        <div className="message-text">
          {message.content || (message.isStreaming ? '...' : '')}
          {message.isStreaming && message.content && <span className="cursor-blink">|</span>}
        </div>
        <div className="message-time">
          {message.timestamp.toLocaleTimeString()}
        </div>
      </div>
    </div>
  )
}
'''.strip()
    )

    # Generate ToolCall.tsx
    write_file(
        f"{output_dir}/frontend/src/l9_ui/chat/ToolCall.tsx",
        '''import { useState } from 'react'
import type { ToolCallInfo } from '../../types'

interface ToolCallProps {
  info: ToolCallInfo
}

export function ToolCall({ info }: ToolCallProps) {
  const [expanded, setExpanded] = useState(false)
  const isRunning = info.status === 'running'

  return (
    <div className={`tool-call ${info.status}`}>
      <div className="tool-call-header" onClick={() => setExpanded(!expanded)}>
        <span className="tool-icon">🔧</span>
        <span className="tool-name">{info.tool}</span>
        {isRunning && <span className="tool-spinner" />}
        {info.status === 'completed' && <span className="tool-check">✓</span>}
        {info.status === 'error' && <span className="tool-error">✗</span>}
        <span className="tool-expand">{expanded ? '▼' : '▶'}</span>
      </div>
      {expanded && (
        <div className="tool-call-details">
          <div className="tool-detail-section">
            <div className="detail-label">输入</div>
            <pre className="detail-content">{info.input}</pre>
          </div>
          {info.output && (
            <div className="tool-detail-section">
              <div className="detail-label">输出</div>
              <pre className="detail-content">{info.output}</pre>
            </div>
          )}
          {info.error && (
            <div className="tool-detail-section error">
              <div className="detail-label">错误</div>
              <pre className="detail-content">{info.error}</pre>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
'''.strip()
    )

    # Generate Header.tsx
    write_file(
        f"{output_dir}/frontend/src/l9_ui/layout/Header.tsx",
        '''interface HeaderProps {
  onToggleSidebar: () => void
  sessionTitle: string
}

export function Header({ onToggleSidebar, sessionTitle }: HeaderProps) {
  return (
    <header className="app-header">
      <button className="sidebar-toggle" onClick={onToggleSidebar}>
        ☰
      </button>
      <h1 className="header-title">{sessionTitle}</h1>
    </header>
  )
}
'''.strip()
    )

    # Generate Sidebar.tsx
    write_file(
        f"{output_dir}/frontend/src/l9_ui/layout/Sidebar.tsx",
        '''import type { Session } from '../../App'

interface SidebarProps {
  sessions: Session[]
  activeSession: string
  onSelect: (id: string) => void
  onCreate: () => void
  onDelete: (id: string) => void
  isOpen: boolean
  onClose: () => void
}

export function Sidebar({ sessions, activeSession, onSelect, onCreate, onDelete, isOpen, onClose }: SidebarProps) {
  return (
    <>
      {isOpen && <div className="sidebar-overlay" onClick={onClose} />}
      <aside className={`sidebar ${isOpen ? 'open' : ''}`}>
        <div className="sidebar-header">
          <h2>会话</h2>
          <button className="new-chat-btn" onClick={onCreate}>+ 新会话</button>
        </div>
        <div className="session-list">
          {sessions.map(session => (
            <div
              key={session.id}
              className={`session-item ${session.id === activeSession ? 'active' : ''}`}
              onClick={() => onSelect(session.id)}
            >
              <span className="session-title">{session.title}</span>
              <button
                className="session-delete"
                onClick={e => { e.stopPropagation(); onDelete(session.id) }}
              >
                ×
              </button>
            </div>
          ))}
        </div>
      </aside>
    </>
  )
}
'''.strip()
    )

    # Generate Loading.tsx
    write_file(
        f"{output_dir}/frontend/src/l9_ui/shared/Loading.tsx",
        '''export function Loading() {
  return (
    <div className="loading">
      <div className="loading-spinner" />
      <span>加载中...</span>
    </div>
  )
}
'''.strip()
    )

    # Generate ErrorBoundary.tsx
    write_file(
        f"{output_dir}/frontend/src/l9_ui/shared/ErrorBoundary.tsx",
        '''import { Component } from 'react'
import type { ReactNode, ErrorInfo } from 'react'

interface Props {
  children: ReactNode
}

interface State {
  hasError: boolean
  error?: Error
}

export class ErrorBoundary extends Component<Props, State> {
  constructor(props: Props) {
    super(props)
    this.state = { hasError: false }
  }

  static getDerivedStateFromError(error: Error): State {
    return { hasError: true, error }
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    console.error('ErrorBoundary caught:', error, errorInfo)
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="error-boundary">
          <h2>出错了</h2>
          <p>{this.state.error?.message}</p>
          <button onClick={() => this.setState({ hasError: false })}>重试</button>
        </div>
      )
    }
    return this.props.children
  }
}
'''.strip()
    )

    # Generate styles/index.css
    write_file(
        f"{output_dir}/frontend/src/styles/index.css",
        '''* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f5f5f5;
  color: #333;
}

/* App container */
.app-container {
  display: flex;
  flex-direction: column;
  height: 100vh;
}

.app-body {
  display: flex;
  flex: 1;
  overflow: hidden;
}

.main-content {
  flex: 1;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

/* Header */
.app-header {
  display: flex;
  align-items: center;
  padding: 0 16px;
  height: 56px;
  background: #fff;
  border-bottom: 1px solid #e0e0e0;
  flex-shrink: 0;
}

.sidebar-toggle {
  background: none;
  border: none;
  font-size: 20px;
  cursor: pointer;
  padding: 8px;
  margin-right: 12px;
}

.header-title {
  font-size: 16px;
  font-weight: 600;
}

/* Sidebar */
.sidebar {
  width: 280px;
  background: #fff;
  border-right: 1px solid #e0e0e0;
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  transition: transform 0.3s;
}

.sidebar-header {
  padding: 16px;
  border-bottom: 1px solid #e0e0e0;
}

.sidebar-header h2 {
  font-size: 14px;
  color: #666;
  margin-bottom: 8px;
}

.new-chat-btn {
  width: 100%;
  padding: 8px;
  background: #0070f3;
  color: #fff;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
}

.session-list {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
}

.session-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 12px;
  border-radius: 6px;
  cursor: pointer;
  margin-bottom: 2px;
}

.session-item:hover { background: #f0f0f0; }
.session-item.active { background: #e3f2fd; }

.session-delete {
  background: none;
  border: none;
  color: #999;
  cursor: pointer;
  font-size: 16px;
}

/* Chat window */
.chat-window {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.messages-container {
  flex: 1;
  overflow-y: auto;
  padding: 20px;
}

.message-bubble {
  display: flex;
  gap: 12px;
  margin-bottom: 20px;
}

.message-bubble.user { flex-direction: row-reverse; }

.message-avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 18px;
  background: #f0f0f0;
  flex-shrink: 0;
}

.message-content {
  max-width: 70%;
}

.message-text {
  padding: 10px 14px;
  border-radius: 12px;
  line-height: 1.5;
  font-size: 14px;
  white-space: pre-wrap;
}

.user .message-text {
  background: #0070f3;
  color: #fff;
  border-bottom-right-radius: 4px;
}

.assistant .message-text {
  background: #fff;
  border: 1px solid #e0e0e0;
  border-bottom-left-radius: 4px;
}

.message-time {
  font-size: 11px;
  color: #999;
  margin-top: 4px;
  padding: 0 4px;
}

.cursor-blink {
  animation: blink 1s infinite;
}

@keyframes blink {
  0%, 50% { opacity: 1; }
  51%, 100% { opacity: 0; }
}

/* Input box */
.chat-input-container {
  display: flex;
  gap: 8px;
  padding: 16px 20px;
  background: #fff;
  border-top: 1px solid #e0e0e0;
}

.chat-input {
  flex: 1;
  padding: 10px 14px;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  resize: none;
  font-size: 14px;
  font-family: inherit;
  outline: none;
  min-height: 40px;
  max-height: 120px;
}

.chat-input:focus { border-color: #0070f3; }

.send-btn {
  padding: 8px 20px;
  background: #0070f3;
  color: #fff;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-size: 14px;
  white-space: nowrap;
}

.send-btn:disabled { background: #ccc; cursor: not-allowed; }

/* Tool calls */
.tool-calls-container {
  margin-left: 44px;
  margin-bottom: 12px;
}

.tool-call {
  background: #fff;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  margin-bottom: 4px;
  overflow: hidden;
}

.tool-call-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  cursor: pointer;
  font-size: 13px;
}

.tool-call.completed .tool-call-header { background: #f0fdf4; }
.tool-call.running .tool-call-header { background: #fff7ed; }

.tool-icon { font-size: 14px; }
.tool-name { flex: 1; }
.tool-check { color: #22c55e; }
.tool-error { color: #ef4444; }
.tool-expand { color: #999; font-size: 10px; }

.tool-call-details {
  padding: 8px 12px;
  border-top: 1px solid #e0e0e0;
  font-size: 12px;
}

.tool-detail-section { margin-bottom: 8px; }
.detail-label { color: #666; margin-bottom: 4px; font-weight: 500; }
.detail-content {
  background: #f9f9f9;
  padding: 8px;
  border-radius: 4px;
  font-size: 11px;
  overflow-x: auto;
  max-height: 200px;
  overflow-y: auto;
}

/* Responsive */
@media (max-width: 768px) {
  .sidebar {
    position: fixed;
    left: 0;
    top: 56px;
    bottom: 0;
    z-index: 100;
    transform: translateX(-100%);
  }
  .sidebar.open { transform: translateX(0); }
  .sidebar-overlay {
    position: fixed;
    inset: 0;
    background: rgba(0,0,0,0.3);
    z-index: 99;
  }
  .message-content { max-width: 85%; }
}
'''.strip()
    )

    # Generate vite.config.ts
    write_file(
        f"{output_dir}/frontend/vite.config.ts",
        '''import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
    },
  },
})
'''.strip()
    )

    # Generate tsconfig.json
    write_file(
        f"{output_dir}/frontend/tsconfig.json",
        '''{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
'''.strip()
    )


def _write_bare_chat(output_dir: str):
    """Write framework-specific chat.py for the bare runtime (AgentEvent contract).

    The default templates/backend/.../chat.py speaks LangGraph astream_events
    (on_chat_model_stream / on_tool_start / ...). The bare runtime emits
    AgentEvent(type=agent_message|tool_call|tool_result|done), so the SSE
    mapping differs. (M0.21 framework-agnostic)
    """
    content = '''"""L8 - Chat API Endpoint (bare framework variant)

SSE streaming chat over the bare AgentRuntime event contract:
  agent_message -> token / done
  tool_call     -> tool_start
  tool_result   -> tool_end
"""

import json
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from ..schemas import ChatRequest
from ...l4_agent.graph import get_graph, get_graph_config
from ...l6_memory.session_manager import get_session_manager
from ...l10_infra.config import settings

router = APIRouter()


@router.post("/chat")
async def chat(request: ChatRequest):
    """Streaming chat (bare runtime: AgentEvent stream over SSE)"""
    # Chat-mode context injection (web / RAG / deep-think / sandbox)
    message = request.message
    mode = request.mode or {}
    ctx_parts = []
    if mode.get("web_search"):
        try:
            from ...l5_tools.base_tools import web_search
            ctx_parts.append(f"[联网搜索结果]\\n{await web_search(request.message)}")
        except Exception as e:
            ctx_parts.append(f"[联网搜索失败: {e}]")
    if mode.get("kb_id"):
        try:
            from ...l6_memory.rag_engine import RAGEngine
            chunks = await RAGEngine().retrieve(request.message, k=5)
            if chunks:
                ctx_parts.append("[知识库引用]\\n" + "\\n".join(f"- {c.text[:300]} (来源: {c.source})" for c in chunks))
            else:
                ctx_parts.append("[知识库] 未检索到相关内容")
        except Exception as e:
            ctx_parts.append(f"[知识库检索失败: {e}]")
    if mode.get("deep_think"):
        ctx_parts.append("[深度思考] 请先给出简要思路与计划，再逐步推理，最后给出明确结论。")
    if mode.get("sandbox") is False:
        ctx_parts.append("[沙箱已关闭] 请勿执行代码，仅给出代码建议。")
    if ctx_parts:
        message = "\\n\\n".join(ctx_parts) + "\\n\\n" + message

    try:
        graph = get_graph()
        session_mgr = get_session_manager()

        thread_id = request.thread_id
        if not thread_id:
            thread_id = session_mgr.create_session()

        config = get_graph_config(thread_id)
        await session_mgr.add_message(thread_id, "user", message)
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))

    async def event_stream():
        tool_call_count = 0
        full_response = ""

        async for ev in graph.stream(
            [{"role": "user", "content": message}], config
        ):
            kind = ev.type
            try:
                if kind == "agent_message":
                    text = ev.content if isinstance(ev.content, str) else ""
                    if text:
                        full_response += text
                        yield f"data: {json.dumps({'type': 'token', 'content': text})}\\n\\n"
                elif kind == "tool_call":
                    tool_call_count += 1
                    data = ev.content or {}
                    yield f"data: {json.dumps({'type': 'tool_start', 'tool': data.get('name'), 'input': str(data.get('input'))[:200]})}\\n\\n"
                elif kind == "tool_result":
                    data = ev.content or {}
                    yield f"data: {json.dumps({'type': 'tool_end', 'tool': data.get('name'), 'output': str(data.get('output'))[:500]})}\\n\\n"
                elif kind == "done":
                    yield f"data: {json.dumps({'type': 'done', 'thread_id': thread_id, 'tool_calls': tool_call_count})}\\n\\n"
            except Exception:
                pass

        if full_response:
            await session_mgr.add_message(thread_id, "assistant", full_response)

        try:
            from ...l10_infra.usage import record_usage
            est_in = max(10, len((request.message or "")) // 2)
            est_out = max(10, len(full_response) // 2)
            record_usage(thread_id, settings.LLM_PROVIDER, settings.LLM_MODEL, est_in, est_out)
        except Exception:
            pass

        yield f"data: {json.dumps({'type': 'done', 'thread_id': thread_id, 'tool_calls': tool_call_count})}\\n\\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")
'''
    dst = f"{output_dir}/app/l8_api/routes/chat.py"
    ensure_dir(os.path.dirname(dst))
    write_file(dst, content)


def _write_bare_tests(output_dir: str):
    """Write framework-specific tests for the bare runtime into the generated project.

    The bare runtime (BareAgentRuntime / get_graph / get_graph_config) only
    exists in generated projects, so its tests ship with the artifact.
    """
    content = '''"""Tests for the bare framework-agnostic runtime compatibility layer.

Covers (M0.21 framework-agnostic):
  - BareAgentRuntime.run / stream / ainvoke event contract
  - get_graph() / get_graph_config() LangGraph-compatible entry points
  - ToolRegistry.get_callables() name -> async callable map
"""

import pytest


@pytest.mark.asyncio
async def test_bare_runtime_stream_event_contract():
    """stream() must emit agent_message -> done with correct payloads."""
    from app.l4_agent.graph import BareAgentRuntime, AgentEvent

    class _FakeResp:
        def __init__(self, content, tool_calls=None, usage=None):
            self.content = content
            self.tool_calls = tool_calls
            self.usage = usage or {}

    class FakeLLM:
        async def invoke(self, messages, tools=None):
            return _FakeResp(content="hello from bare")

    runtime = BareAgentRuntime(llm_factory=lambda: FakeLLM(), tools={})
    events = []
    async for ev in runtime.stream(
        [{"role": "user", "content": "hi"}], {"thread_id": "t-bare-1"}
    ):
        assert isinstance(ev, AgentEvent)
        events.append(ev)

    types = [e.type for e in events]
    assert types[-1] == "done"
    assert "agent_message" in types
    assert events[-1].content["latency_ms"] >= 0


@pytest.mark.asyncio
async def test_bare_runtime_tool_call_roundtrip():
    """tool_call / tool_result events must be emitted when the LLM asks for tools."""
    from app.l4_agent.graph import BareAgentRuntime

    class _FakeResp:
        def __init__(self, content, tool_calls=None, usage=None):
            self.content = content
            self.tool_calls = tool_calls
            self.usage = usage or {}

    class FakeLLM:
        def __init__(self):
            self.calls = 0

        async def invoke(self, messages, tools=None):
            self.calls += 1
            if self.calls == 1:
                return _FakeResp(
                    content="",
                    tool_calls=[{
                        "name": "echo_tool",
                        "arguments": {"text": "ping"},
                        "id": "call_1",
                    }],
                )
            return _FakeResp(content="tool result used: ping")

    async def echo_tool(text: str) -> str:
        return f"echoed:{text}"

    runtime = BareAgentRuntime(llm_factory=lambda: FakeLLM(), tools={"echo_tool": echo_tool})
    types, payloads = [], []
    async for ev in runtime.stream([{"role": "user", "content": "call tool"}], {}):
        types.append(ev.type)
        payloads.append(ev.content)

    assert "tool_call" in types
    assert "tool_result" in types
    idx_call = types.index("tool_call")
    idx_result = types.index("tool_result")
    assert payloads[idx_call]["name"] == "echo_tool"
    assert payloads[idx_result]["output"] == "echoed:ping"


@pytest.mark.asyncio
async def test_bare_ainvoke_langgraph_contract():
    """ainvoke() must return {'messages': [...]} like LangGraph for L7/L8 routes."""
    from app.l4_agent.graph import BareAgentRuntime

    class _FakeResp:
        def __init__(self, content, tool_calls=None, usage=None):
            self.content = content
            self.tool_calls = tool_calls
            self.usage = usage or {}

    class FakeLLM:
        async def invoke(self, messages, tools=None):
            return _FakeResp(content="answer")

    runtime = BareAgentRuntime(llm_factory=lambda: FakeLLM(), tools={})
    result = await runtime.ainvoke(
        {"messages": [("user", "question")]}, {"thread_id": "t-ainvoke"}
    )
    assert "messages" in result
    assert result["messages"][-1]["content"] == "answer"


def test_bare_get_graph_config():
    """get_graph_config() must return a LangGraph-style config dict."""
    from app.l4_agent.graph import get_graph_config

    cfg = get_graph_config("thread-xyz")
    assert cfg == {"thread_id": "thread-xyz"}


def test_tool_registry_get_callables():
    """ToolRegistry.get_callables() must expose async callables by name."""
    from app.l5_tools.registry import ToolRegistry

    class FakeTool:
        name = "fake_tool"
        description = "fake"

        async def ainvoke(self, kwargs):
            return f"called:{kwargs}"

    ToolRegistry.clear()
    ToolRegistry.register(FakeTool(), category="test")
    callables = ToolRegistry.get_callables()
    assert "fake_tool" in callables
    ToolRegistry.clear()
'''
    dst = f"{output_dir}/tests/test_bare_runtime.py"
    ensure_dir(os.path.dirname(dst))
    write_file(dst, content)


def copy_static_templates(output_dir: str, framework: Optional[str] = None):
    """Copy static template files that don't need modification.

    Copies the ENTIRE templates/backend/app tree so every support file (errors,
    monitoring, middlewares, routes, adapters, ...) is present in the generated
    project, EXCEPT the files that generate_*() emits (they were already
    written into output_dir and take precedence). This keeps the generated
    project fully importable regardless of which routers are mounted.

    Args:
        output_dir: generated project root
        framework: agent framework ('bare' needs framework-specific chat.py)
    """
    # Files produced by generate_*() — never overwrite with the static copy.
    GENERATED = {
        "main.py",
        "l3_prompt/system_prompts.py",
        "l10_infra/config.py",
        "l4_agent/graph.py",
        "l5_tools/base_tools.py",
        "l5_tools/custom_tools.py",
    }

    app_src = TEMPLATES_DIR / "backend" / "app"
    app_dst = Path(output_dir) / "app"
    for root, dirs, files in os.walk(str(app_src)):
        rel_root = os.path.relpath(root, str(app_src))
        for name in files:
            rel = os.path.normpath(os.path.join(rel_root, name))
            if rel in GENERATED:
                continue
            src = os.path.join(root, name)
            dst = os.path.join(str(app_dst), rel)
            ensure_dir(os.path.dirname(dst))
            copy_template(src, dst)

    # Backend-level support files
    for name in ["requirements.txt", "Dockerfile"]:
        src = TEMPLATES_DIR / "backend" / name
        if src.exists():
            ensure_dir(output_dir)
            copy_template(str(src), os.path.join(output_dir, name))

    # Scripts
    scripts_src = TEMPLATES_DIR / "backend" / "scripts"
    for f in os.listdir(str(scripts_src)):
        src = scripts_src / f
        if src.is_file():
            dst = f"{output_dir}/scripts/{f}"
            ensure_dir(os.path.dirname(dst))
            copy_template(str(src), dst)

    # ------------------------------------------------------------------
    # Frontend: copy the FULL canonical template frontend (admin console +
    # workspace + chat + all API/types) over the minimal chat-only frontend
    # emitted by generate_frontend(). This makes the generated project's UI
    # feature-complete and keeps it in sync with the template.
    # ------------------------------------------------------------------
    fe_src = TEMPLATES_DIR / "frontend"
    fe_dst = Path(output_dir) / "frontend"
    for root, dirs, files in os.walk(str(fe_src)):
        # Prune build artifacts / deps so they are never copied into output.
        dirs[:] = [d for d in dirs if d not in ("node_modules", "dist", ".vite")]
        rel_root = os.path.relpath(root, str(fe_src))
        for name in files:
            if name in ("node_modules", "dist"):
                continue
            rel = os.path.normpath(os.path.join(rel_root, name))
            src = os.path.join(root, name)
            dst = os.path.join(str(fe_dst), rel)
            ensure_dir(os.path.dirname(dst))
            copy_template(src, dst)

    # Bare framework: chat.py must use the while-loop stream() event contract
    # (AgentEvent: agent_message/tool_call/tool_result/done) instead of the
    # LangGraph astream_events contract. (M0.21 framework-agnostic)
    if framework == "bare":
        _write_bare_chat(output_dir)
        _write_bare_tests(output_dir)



# ============================================================
# Main entry
# ============================================================

def main():
    # Optional --framework flag: choose the agent runtime framework (M0.21)
    # Default: None -> interactive selection prompt (framework-agnostic, not defaulting to LangChain)
    framework = None
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = [a for a in sys.argv[1:] if a.startswith("--")]
    for f in flags:
        if f == "--framework":
            print("Error: --framework requires a value, e.g. --framework langgraph")
            sys.exit(1)
        if f.startswith("--framework="):
            framework = f.split("=", 1)[1]
        elif f == "--framework-list":
            print("Available frameworks (M0.21):")
            print("  langgraph       - LangGraph 1.0 (StateGraph/Command/checkpoint)")
            print("  openai-agents   - OpenAI Agents SDK (Agent+Handoffs+Guardrails)")
            print("  claude-sdk      - Claude Agent SDK (Agent Loop+Subagent+hooks)")
            print("  adk             - Google ADK (Agent+RemoteA2AAgent)")
            print("  autogen         - AutoGen/AG2 (GroupChat multi-agent)")
            print("  bare            - 自研核心（自己的 while-loop 工具循环，无框架依赖）")
            print("")
            print("详见 docs/framework-selection.md 框架全景矩阵与决策树")
            sys.exit(0)

    if len(args) < 2:
        print("Usage: python scripts/generate.py <config.yaml> <output_dir> [--framework=<name>]")
        print("")
        print("Example:")
        print("  python scripts/generate.py agent.yaml ./generated_agent --framework=langgraph")
        print("  python scripts/generate.py agent.yaml ./generated_agent --framework=bare")
        print("  python scripts/generate.py agent.yaml ./generated_agent --framework-list")
        print("")
        print("未指定 --framework 时进入交互式选择（不默认 LangChain，见 docs/framework-selection.md）")
        sys.exit(1)

    config_path = args[0]
    output_dir = args[1]

    if not os.path.exists(config_path):
        print(f"Error: Config file does not exist: {config_path}")
        sys.exit(1)

    print(f"Loading config: {config_path}")
    config = load_config(config_path)

    # Framework selection: yaml field > --framework flag > interactive prompt
    if framework is None:
        framework = config.get("framework") or config.get("agent_framework", {}).get("name")
    if framework is None:
        framework = _interactive_framework_select()
    config["framework"] = framework
    print(f"Agent framework: {framework}")

    agent_name = config.get("agent", {}).get("name", "Agent")
    agent_type = config.get("agent", {}).get("type", "chat")
    print(f"Agent: {agent_name} ({agent_type})")
    print("")

    # Clean and create output directory
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir, exist_ok=True)

    # Copy config file and requirements docs to output directory
    shutil.copy2(config_path, f"{output_dir}/agent.yaml")
    print(f"  ✓ Copied: {config_path} → {output_dir}/agent.yaml")

    print("")
    print("=== Starting code generation ===")
    print("")

    # Generate layer by layer in L1 → L10 order
    print("[L1] LLM layer...")
    generate_l1_llm(config, output_dir)

    print("[L3] Prompt engineering layer...")
    generate_l3_prompt(config, output_dir)

    print("[L4] Agent framework layer...")
    generate_l4_agent(config, output_dir)

    print("[L5] Tool execution layer...")
    generate_l5_tools(config, output_dir)

    print("[L8] API service layer + [L10] infrastructure layer...")
    generate_l8_api(config, output_dir)
    generate_l10_infra(config, output_dir)

    print("[L9] Frontend presentation layer...")
    generate_frontend(config, output_dir)

    print("")
    print("=== Copying static template files ===")
    copy_static_templates(output_dir, framework)

    print("")
    print(f"=== Generation complete! ===")
    print(f"Output directory: {output_dir}")
    print("")
    print("How to start:")
    print(f"  cd {output_dir}")
    print("  cp .env.example .env  # Edit and fill in your API Key")
    print("  pip install -r requirements.txt")
    print("  uvicorn app.main:app --reload --port 8000")
    print("")
    print("  cd frontend")
    print("  npm install && npm run dev")
    print("")
    print("  # Or use Docker:")
    print("  docker-compose up --build")


if __name__ == "__main__":
    main()
